default:
  actions: []
  cooldown: 10
  enabled: false
  min_duration: 0
rules:
  person:
    actions:
    - subdir: ''
      type: audio
    - message: STEAM_DETECT_PERSON
      type: udp
    cooldown: 5
    enabled: false
    min_duration: 2
  plate_bougie:
    actions:
    - message: STEAM_CARD_BOUGIE
      type: udp
    - subdir: bougie
      type: video
    - subdir: bougie
      type: audio
    cooldown: 8
    enabled: true
    min_duration: 0
  plate_cellule:
    actions:
    - message: STEAM_CARD_CELLULE
      type: udp
    - subdir: cellule
      type: video
    - subdir: cellule
      type: audio
    cooldown: 8
    enabled: true
    min_duration: 0
  plate_chaudron:
    actions:
    - message: STEAM_CARD_CHAUDRON
      type: udp
    - subdir: chaudron
      type: video
    - subdir: chaudron
      type: audio
    cooldown: 8
    enabled: true
    min_duration: 0
  plate_dague:
    actions:
    - message: STEAM_CARD_DAGUE
      type: udp
    - subdir: dague
      type: video
    - subdir: dague
      type: audio
    cooldown: 8
    enabled: true
    min_duration: 0
  plate_vampire:
    actions:
    - message: STEAM_CARD_VAMPIRE
      type: udp
    - subdir: vampire
      type: video
    - subdir: vampire
      type: audio
    cooldown: 8
    enabled: true
    min_duration: 0
